### ISSUE TITLE
More similarities

### ISSUE THREAD

**Issue by z1mvader** [z1mvader/quackin#5]
Currently in the metrics module the only available similarity is the cosine similarity. Quackin should support other similarities like Jaccard and Pearson correlation,

**Comment by chrisvittal** [comment]
I'd be willing to take this. Are there any other similarities you would like me to add?

**Comment by z1mvader** [comment]
Hi! I suggested those similarities because they are the "mainstream" ones, I'd be happy to hear if you have any other in mind. 

Regarding the implementation just be sure the similarities do not return nan/inf values. For example, cosine is returning 0 when one of the vectors is zero. 

Thanks for your interest :)

**Comment by DarkDrek** [comment]
I am trying to implement the Jaccard similarity [from wikipedia](https://en.wikipedia.org/wiki/Jaccard_index#Generalized_Jaccard_similarity_and_distance) but all values have to be >= 0 for the algorithm to work. How should I handle negative numbers in the `CsVecOwned<f64>` arguments?

**Comment by z1mvader** [comment]
Jmmm in principle that "shouldn't" be a problem because usually the vectors passed to those similarities are always positive (at least for the basic collaborative filtering algorithms). But we should add a little disclaimer in the docs

**Comment by z1mvader** [comment]
I just implemented Pearson on https://github.com/z1mvader/quackin/commit/546c4cd6d8ca8efdf4742c70301fd9e36359e7d8. I believe these are enough similarities at least for now. Thanks for your interest :P
