### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [z1mvader/quackin#8]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by z1mvader** [comment]
hey hi! Thanks for your Issue. Currently it's using it because the version of the `csv` crate used by `quackin` requires it. It also was a dependency because in 0.1.1 the struct for storing the records it was required to be `serializable` using `rustc-serialize`. Let me clean that
